/*
-- MODULE: bitstream_upload.ino
-- FUNCTION: upload bitstream to SPI flash
-- AUTHOR: Jakob Kieszek Ottesen
-- CREATED: 2026-05-11 (YYYY-MM-DD)
-- MODIFIED: 2026-05-14

Arduino: Pro Micro

Circuit:
  CS#: pin 10    DEFAULT (explicitly defined below)
  MOSI: pin 16   DEFAULT
  MISO: pin 14   DEFAULT
  SCK: pin 15    DEFAULT
  GND: important with common ground between arduino, voltage dividers and FPGA PCB

  Voltage divider used for lines: CS#, MOSI, and SCK (signals generated by Arduino)
  
  Arduino output -- 220 ohm -- 220 ohm -- + -- FPGA/flash input
                                          |
                                        330 ohm
                                          |
                                        330 ohm
                                          |
                                         GND
  
  This gives ~3V instead of 5V output from the Arduino, preventing backpowering of the PCB
    5V * 660 / (440 + 660) = 3.0V
  
  Downside: low-value divider which burns more current. Specifically ~4.5mA (5V / 1100ohms ~= 4.5mA)

 */

#include <SPI.h>  // arduino and flash communicate via SPI, so include the library:

const int SPI_SPEED = 100000;
const int chipSelectPin = 10;

SPISettings flashSPI(100000, MSBFIRST, SPI_MODE0);  // 100kHz

uint8_t pageBuf[256];     // stores incoming page data from Python
uint8_t verifyBuf[256];   // stores flash readback data for comparison


void readJEDEC(uint8_t *id) {
  // Reads flash JEDEC ID. Expecting 239 (0xEF), 64 (0x40), 19 (0x13)
  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0x9F);  // JEDEC ID request
  id[0] = SPI.transfer(0x00);
  id[1] = SPI.transfer(0x00);
  id[2] = SPI.transfer(0x00);
  digitalWrite(chipSelectPin, HIGH);
  // delayMicroseconds(1);
  SPI.endTransaction();
}

uint8_t readStatus1() {
  // Read status register 1
  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0x05);
  uint8_t status = SPI.transfer(0x00);
  digitalWrite(chipSelectPin, HIGH);
  delayMicroseconds(1);
  SPI.endTransaction();
  return status;
}

void writeEnable() {
  // Required for every page program, sector erase, block erase, chip erase, write status register and erase/program security registers instruction
  // WEL (write enable latch) is automatically reset after power-up and upon compltion of the write status registe, erase/program security registers, ...
  // ... page program, sector erase, block erase and chip erase instructions
  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0x06);
  digitalWrite(chipSelectPin, HIGH);
  delayMicroseconds(1);
  SPI.endTransaction();
}

void releasePowerDownAB() {
  // Release SPI flash from power down
  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0xAB);  // release power down
  digitalWrite(chipSelectPin, HIGH);
  delayMicroseconds(1);
  SPI.endTransaction();
  delayMicroseconds(5);
}

uint8_t readDeviceIdAB() {
  // Release SPI flash from power down and wait for 4th byte (unique flash ID)
  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0xAB);
  SPI.transfer(0x00);
  SPI.transfer(0x00);
  SPI.transfer(0x00);
  uint8_t id = SPI.transfer(0x00);
  digitalWrite(chipSelectPin, HIGH);
  delayMicroseconds(1);
  SPI.endTransaction();
  return id;
}

void printHexByte(uint8_t value) {
  // Formats value to hex value and prints to serial interface
  Serial.print("0x");
  if (value < 0x10) Serial.print("0");
  Serial.print(value, HEX);
}

void printHexByteln(uint8_t value) {
  // Formats value to hex value and prints to serial interface
  // Adds newline to the end
  Serial.print("0x");
  if (value < 0x10) Serial.print("0");
  Serial.println(value, HEX);
}

void waitBusyClear() {
  // Waits until status bit 1 (BUSY bit) goes low (high during sector erase cycle / page program cycle; low when the cycle is finished)
  while (readStatus1() & 0x01) {
    delay(1);
  }
}

void sendAddress(uint32_t addr) {
  // Uses uint32_t because no uint24_t available. Address is 24 bits long
  SPI.transfer((addr >> 16) & 0xFF);
  SPI.transfer((addr >> 8) & 0xFF);
  SPI.transfer(addr & 0xFF);
}

void sectorErase4k(uint32_t addr) {
  // Erase 4kB sector with address addr
  writeEnable();

  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0x20);
  sendAddress(addr);
  digitalWrite(chipSelectPin, HIGH);
  delayMicroseconds(1);
  SPI.endTransaction();

  waitBusyClear();
}

void pageProgram(uint32_t addr, const uint8_t *data, uint16_t len) {
  // You can program one page at a time. 16 pages per sector (sector is referenced by address addr)
  // len must be <= 256 and must not cross a 256-byte page boundary
  writeEnable();

  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0x02);
  sendAddress(addr);  // address of sector to which you want to write data
  // TODO: I don't understand how you would be able to program multiple pages within the same sector address...

  for (uint16_t i = 0; i < len; i++) {
    SPI.transfer(data[i]);
  }

  digitalWrite(chipSelectPin, HIGH);
  delayMicroseconds(1);
  SPI.endTransaction();

  waitBusyClear();
}

void readData(uint32_t addr, uint8_t *buf, uint16_t len) {
  // Read data from sector with address addr. Read this data (of length len) into buffer buf
  SPI.beginTransaction(flashSPI);
  digitalWrite(chipSelectPin, LOW);
  SPI.transfer(0x03);
  sendAddress(addr);  // address of sector from which you want to read data

  for (uint16_t i = 0; i < len; i++) {
    buf[i] = SPI.transfer(0x00);
  }

  digitalWrite(chipSelectPin, HIGH);
  delayMicroseconds(1);
  SPI.endTransaction();
}

void confirmFlashCommunication() {
  // -------------------------------------------------------------------------
  // DIAGNOSTICS / confirm flash resopnse ------------------------------------
  // -------------------------------------------------------------------------

  uint8_t JEDEC_buf[3] = {0};
  readJEDEC(JEDEC_buf);
  Serial.println("JEDEC ID request command (0x9F) written to to SPI flash");
  Serial.print("Received (expecting 0xEF, 0x40, 0x13): ");
  printHexByte(JEDEC_buf[0]);
  Serial.print(" ");
  printHexByte(JEDEC_buf[1]);
  Serial.print(" ");
  printHexByteln(JEDEC_buf[2]);

  releasePowerDownAB();
  Serial.println("Release power down command (0xAB) written to SPI flash");

  Serial.print("AB Device ID (expecting 0x12): ");
  printHexByteln(readDeviceIdAB());

  Serial.print("Status before WREN (expecting 0x00): ");
  uint8_t before_status = readStatus1();
  printHexByteln(before_status);

  writeEnable();
  Serial.println("Write enable command (0x06) written to SPI flash");

  Serial.print("Status after WREN (expecting 0x02): ");
  uint8_t after_status = readStatus1();
  printHexByteln(after_status);
}

void testEraseReadProgramRead() {
  // -------------------------------------------------------------------------
  // Micro-test: erase + read; program + read --------------------------------
  // -------------------------------------------------------------------------
  uint8_t buffer[16] = {0};

  uint8_t testPattern[16] = {
    0x00, 0x11, 0x22, 0x33,
    0x44, 0x55, 0x66, 0x77,
    0x88, 0x99, 0xAA, 0xBB,
    0xCC, 0xDD, 0xEE, 0xFF
  };

  Serial.println("Erasing sector 0...");
  sectorErase4k(0x000000);

  Serial.println("Reading after erase...");
  readData(0x000000, buffer, 16);

  Serial.print("Erase readback: ");
  for (int i = 0; i < 16; i++) {
    if (buffer[i] < 0x10) Serial.print("0");
    Serial.print(buffer[i], HEX);
    Serial.print(" ");
  }
  Serial.println();

  Serial.println("Programming test pattern...");
  pageProgram(0x000000, testPattern, 16);

  Serial.println("Reading after program...");
  readData(0x000000, buffer, 16);

  Serial.print("Program readback: ");
  for (int i = 0; i < 16; i++) {
    if (buffer[i] < 0x10) Serial.print("0");
    Serial.print(buffer[i], HEX);
    Serial.print(" ");
  }
  Serial.println();

  bool pass = true;
  for (int i = 0; i < 16; i++) {
    if (buffer[i] != testPattern[i]) {
      pass = false;
    }
  }

  if (pass) {
    Serial.println("PASS: readback matches test pattern");
  } else {
    Serial.println("FAIL: readback mismatch");
  }
}



void setup() {
  Serial.begin(115200);

  // Explicitly set inputs/outputs
  pinMode(16, OUTPUT);                // MOSI
  pinMode(15, OUTPUT);                // SCK
  pinMode(14, INPUT);                 // MISO
  pinMode(chipSelectPin, OUTPUT);     // CS#
  digitalWrite(chipSelectPin, HIGH);  // default high

  SPI.begin();  // start the SPI library
  delay(1000);  // give the SPI flash time to set up

  confirmFlashCommunication();  // MUST BE COMMENTED OUT DURING PROPER FLASH PROGRAMMING!
  testEraseReadProgramRead();   // MUST BE COMMENTED OUT DURING PROPER FLASH PROGRAMMING!

  
  /*

  // -------------------------------------------------------------------------
  // ERASE + PROGRAM  --------------------------------------------------------
  // -------------------------------------------------------------------------

  // bitmap file size: 104,157 bytes --> / 4096 (sector size) --> 26 x (4k) sectors
  // 104,157 bytes / 256 bytes per page = 407 pages (only 221/256 bytes on last page)
  // Numbers to keep in mind: 26 (4k) sectors. 16 (256 byte) pages per sector. 256 bytes per page.

  uint8_t py_data[256] = {0}

  for (int i = 0; i < 26, i++) {  // 26 sectors
    // erase sector
    sectorErase4k(i);

    for (int j = 0, j < 16, j++) {  // 16 pages per sector
      // program 1 page (256 bytes) after receiving said bytes from python script on serial line
      for (int k = 0, k < 256, k++) {  // 256 data bytes per page
        if (Serial.available() > 0) {
          char incomingByte = Serial.read();  // Read one byte
          py_data[k] = incomingByte;

          if k == 255 {  // page program when full py_data array of 256 bytes
            pageProgram(j, py_data, 256);
          }
        }
      }
    }
  }

  // -------------------------------------------------------------------------
  // VERIFY ------------------------------------------------------------------
  // -------------------------------------------------------------------------

  // read back addresses from SPI flash
  for (int i = 0; i < 26, i++) {
    readData(i, <buf>, <length>);
  }
  */

}

void loop() {
  Serial.println("In loop");
  delay(5000);
}


